imports:
    - { resource: config.yml }

parameters:
    mailer_user: "%mailer_user%"
    mailer_password: "%mailer_password%"

doctrine:
    orm:
        metadata_cache_driver: apcu
        result_cache_driver: apcu
        query_cache_driver: apcu
    dbal:
        url: "%database_url%"

monolog:
    handlers:
        main:
            type:         fingers_crossed
            action_level: error
            handler:      nested
        nested:
            type:  stream
            path:  "php://stderr"
            level: debug
        console:
            type:  console
