hunter_entity:
    resource: "@HunterEntityBundle/Resources/config/routing.yml"
    prefix:   /

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

hunter_frontend:
    resource: "@HunterFrontendBundle/Resources/config/routing.yml"
    prefix:   /

hunter_backend:
    resource: "@HunterBackendBundle/Resources/config/routing.yml"
    prefix:   /admin