hunter_frontend:
    resource: "@HunterFrontendBundle/Resources/config/routing.yml"
    prefix:   /

hunter_backend:
    resource: "@HunterBackendBundle/Resources/config/routing.yml"
    prefix:   /admin