# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
    app.intl_extension:
        class: Twig_Extensions_Extension_Intl
        public: false
        tags:
          - { name: twig.extension }
