services:
  hunter_frontend.menu_builder:
    class: Hunter\FrontendBundle\Menu\Builder
    arguments: ['@knp_menu.factory']
    tags:
      - { name: knp_menu.menu_builder, method: createNavMenu, alias: nav }