hunter_backend_product_index:
    path:     /
    defaults: { _controller: "HunterBackendBundle:Product:index" }
    methods:  GET

hunter_backend_product_show:
    path:     /{id}/show
    defaults: { _controller: "HunterBackendBundle:Product:show" }
    methods:  GET

hunter_backend_product_new:
    path:     /new
    defaults: { _controller: "HunterBackendBundle:Product:new" }
    methods:  [GET, POST]

hunter_backend_product_edit:
    path:     /{id}/edit
    defaults: { _controller: "HunterBackendBundle:Product:edit" }
    methods:  [GET, POST]

hunter_backend_product_delete:
    path:     /{id}/delete
    defaults: { _controller: "HunterBackendBundle:Product:delete" }
    methods:  DELETE
