hunter_backend_homepage:
    path:     /
    defaults: { _controller: HunterBackendBundle:Default:index }

hunter_backend_product:
    resource: "@HunterBackendBundle/Resources/config/routing/product.yml"
    prefix:   /shop/products

hunter_backend_product_category:
    resource: "@HunterBackendBundle/Resources/config/routing/product_category.yml"
    prefix:   /shop/categories