services:
    hunter_backend.menu_builder:
        class: Hunter\BackendBundle\Menu\MenuBuilder
        arguments:
            - "@knp_menu.factory"
        tags:
            - { name: knp_menu.menu_builder, method: createNavbarMenu, alias: navbar }